services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=INFO
      - SERVER_ADDRESS=0.0.0.0:8080
      - SHUTDOWN_TIMEOUT=15s
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=review-assigner-db
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    networks:
      - new

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=review-assigner-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      new:
        aliases:
          - database
  
  migrations:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations:Z
    command:
      - -path=/migrations
      - -database=postgresql://postgres:${DB_PASSWORD}@db:5432/review-assigner-db?sslmode=disable
      - up
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - new

volumes:
  postgres_data:

networks:
  new: